version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: unclepay_postgres
    restart: always
    environment:
      POSTGRES_USER: uncledev
      POSTGRES_PASSWORD: Pyrexer__133
      POSTGRES_DB: unclepay
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U uncledev']
      interval: 10s
      timeout: 5s

volumes:
  postgres_data:
